name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  zlint:
    name: zlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Install zlint
        run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash -s -- v0.7.9

      - name: Run zlint
        run: zlint
